apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  init-db.js: |
    // Initialize MongoDB database
    db = db.getSiblingDB('cybersecurity_db');
    
    db.createCollection('predictions', { 
        capped: true, 
        size: 4294967296  // 4Gi
    });
    
    db.predictions.createIndex({ 'attack_type': 1 });
    db.predictions.createIndex({ 'timestamp': -1 });
    db.predictions.createIndex({ 'confidence': -1 });
    db.predictions.createIndex({ 'kafka_metadata.offset': -1 });
    
    // Create alerts collection
    db.createCollection('alerts');
    db.alerts.createIndex({ 'created_at': -1 });
    db.alerts.createIndex({ 'attack_type': 1 });

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: "mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongodb
        
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          value: "cybersecurity_db"
        
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /docker-entrypoint-initdb.d
        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - mongosh -u admin -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - mongosh -u admin -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      
      volumes:
      - name: mongodb-config
        configMap:
          name: mongodb-config
  
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb


