apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spark-worker-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spark-worker
  minReplicas: 1   # Minimum de workers au repos
  maxReplicas: 10  # Maximum de workers en cas de pic de données
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Scale si le CPU moyen dépasse 70%